apiVersion: v1
kind: Service
metadata:
  labels:
    app: bytegolf
  name: bytegolf
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: bytegolf
  sessionAffinity: None
  type: LoadBalancer
