port: "6017"
users:
  use-aws: true
  table: "bytegolf-users"
  region: "us-east-1"
questions:
  use-aws: true
  table: "bytegolf-questions"
  region: "us-east-1"
storage:
  save-submissions: true
  save-logs: true