FROM node:18.12.1-alpine3.15 as build

COPY . .
WORKDIR /frontend

# COPY frontend/ ./
RUN npm install 
RUN npm run build

# FROM gcr.io/google.com/cloudsdktool/cloud-sdk:slim
# COPY --from=build /build /build

# WORKDIR /build

# ENV BUCKET_NAME bytegolf

# RUN if gsutil -q stat "gs://${BUCKET_NAME}"; then gsutil -m rm -r "gs://${BUCKET_NAME}/**"; fi 
# RUN gsutil -m cp -r . "gs://${BUCKET_NAME}"

COPY frontend/build/ /output