FROM golang:1.19.5-alpine3.17 as build
ADD . /bytegolf
WORKDIR /bytegolf/compiler

RUN go mod vendor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o compiler

FROM alpine:latest
USER root
COPY --from=build /bytegolf/compiler/compiler .

ENV app=compiler

CMD ["./compiler"]