FROM golang:1.19.5-alpine3.17 as build
ADD . /bytegolf
WORKDIR /bytegolf/startup

RUN go mod vendor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o startup

FROM alpine:latest
COPY --from=build /bytegolf/startup/startup .
COPY --from=build /bytegolf/startup/languages.yaml .

ENV app=startup

CMD ["./startup"]